### ISSUE TITLE
Not fetching full URL

### ISSUE THREAD

**Issue by dlman** [cryzed/Selenium-Requests#15]
For example:

`response = webdriver.request('GET', 'http://stats.nba.com/game/#!/0021500004/')`

will only return the contents of http://stats.nba.com/

Using Chrome driver.

**Comment by cryzed** [comment]
That happens because the parts after the `#` are most likely interpreted by on-site JavaScript -- when doing a low-level `GET` request the information is simply discarded. Whatever you are attempting, you'll have to figure out what the JavaScript does with that last bit of information and emulate it.

**Comment by hhankj2u** [comment]
I think the problem come from this, *window.open* just have schema and netloc only
![image](https://user-images.githubusercontent.com/10140299/33888501-d3c1856a-df7f-11e7-92d7-b093385125d7.png)

If I change it to below, it's works fine.
```
self.execute_script("window.open('%s');" % (url))
```


*urlparse* function:
![image](https://user-images.githubusercontent.com/10140299/33888657-4ae72d0c-df80-11e7-8438-b2dadf9661b4.png)
