### ISSUE TITLE
Time out for login.live.com

### ISSUE THREAD

**Issue by huilinchen98** [cryzed/Selenium-Requests#21]
I'm able to open _login.live.com_ successfully using the browser. I'm also able to get the response code through urllib. But when I try to use this package to get the response code it times out. It might because this website forces us to use https protocol.

**Comment by cryzed** [comment]
So the following works without issues for me:

```python
import seleniumrequests

webdriver = seleniumrequests.Chrome()
response = webdriver.request('GET', 'https://login.live.com/')
print(response.status_code)

response = webdriver.request('GET', 'http://login.live.com/')
print(response.status_code)
```

With the git-version. Please run the following:
`$ pip install https://github.com/cryzed/Selenium-Requests/archive/master.zip --upgrade`

and then try running the above snippet. The issue lies most likely with the webdriver you are using (I suspect PhantomJS), please try Chrome or Chromium and let me know if it works. If it does, try reading up on the headless version of Chromium (which does not spawn a graphical interface and works similarly to PhantomJS just... much better).

**Comment by huilinchen98** [comment]
I tried and it works with Chrome. I was using firefox earlier.

**Comment by cryzed** [comment]
So this is a webdriver-specific bug, unfortunately not really something I can fix.
