### ISSUE TITLE
Tab closing after request

### ISSUE THREAD

**Issue by Eastkap** [cryzed/Selenium-Requests#22]
So when I requests an URL through 
`response = webdriver.request('GET', 'https://www.google.com/')`
I have the webdriver loading the site, but once it has loaded it, the tab closes by itself. Is there a way to sit on the tab? I can't find so...

**Comment by cryzed** [comment]
Yes, there is. If you check out the [README](https://github.com/cryzed/Selenium-Requests/blob/master/README.md) you'll see that this actually a feature: "All operations preserve the original state of the WebDriver (active window handle and window handles)". The tab is only opened and then immediately closed, to get access to the stored cookies for that domain (this is a requirement of the WebDriver protocol specification). If you want to open a tab, and keep it open, simply open it as you usually would beforehand:

```python
webdriver.get('https://www.google.com/')
response = webdriver.request('GET', 'https://www.google.com/')
```

You'll also notice that no new additional tab will be opened in this case, because an active handle with the matching domain already exists.

**Comment by Eastkap** [comment]
I see, thing is, when I post through this line: 
`response = webdriver.request('POST',url=url, allow_redirects=True,data=payload)`
I want the browser to site on the website, since there is a javascript essential that is going to run on the window where the request was sent.

**Comment by cryzed** [comment]
So do I what I explained above, the browser will "sit on the website". If the browser needs to sent the POST request through some JavaScript magic, you'll have to manually trigger the JavaScript from the webdriver using `js_eval`.

**Comment by Eastkap** [comment]
Actually, in short what I would need is the newly opened tab not to close

**Comment by cryzed** [comment]
What you are trying to do doesn't make sense, the tab that opens is simply the domain of the website to get access to the cookies if a window handle for that domain is not already opened. Despite what you think, it's almost completely unrelated to the actual `POST`-request that you are attempting.

**Comment by Eastkap** [comment]
Damn ok I see!

**Comment by cryzed** [comment]
As I have mentioned, check out how the JavaScript on the website works (or would usually work if you the request "by hand") and trigger this behavior manually using the webdriver, either through directly evaluating custom JavaScript or interacting with the elements.

**Comment by Eastkap** [comment]
I injected some code through Javascript finally! All good! Good module also!
