### ISSUE TITLE
seleniumrequests fails when used with SOCKS

### ISSUE THREAD

**Issue by mjuarezm** [cryzed/Selenium-Requests#24]
I have set up an SSH tunnel with SOCKS by doing:

`ssh -4 -f -N -D 9991 remotehost`

When I try to use `seleniumrequests` to fetch a site through the SOCKS proxy (see below), the driver opens a tab to localhost:`<seemingly random port>`.

```
from seleniumrequests import Chrome
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument('--proxy-server=socks5://localhost:9991')

ch = Chrome(options=options)
ch.request('GET', 'http://google.com')
```
It does work, however, when I use Selenium driver's get method and, interestingly, the code above also works if the SOCKS sever is in localhost (e.g., `ssh -4 -f -N -D 9991 localhost`).

**Comment by cryzed** [comment]
The tab to localhost is opened to grab the default headers sent by the browser, it should almost immediately close and then open the requested URL (you can see this in the README). It might not do that, because when specifying a proxy-server using `--proxy-server`, Chrome might attempt to even load localhost connections through it, unless excluded by something like `--proxy-bypass-list`. Let me know if that works. Otherwise, try using [requestium](https://github.com/tryolabs/requestium).

**Comment by mjuarezm** [comment]
thanks @cryzed for the quick answer. I will try by setting `--proxy-bypass-list` and let you know.

**Comment by mjuarezm** [comment]
Yup. This does work:

```
from seleniumrequests import Chrome
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument('--proxy-server=socks5://localhost:9991')
options.add_argument('--proxy-bypass-list=127.0.0.1')

ch = Chrome(options=options)
ch.request('GET', 'http://google.com')
```

Thank you!
