### ISSUE TITLE
Getting error when trying to pass query string params

### ISSUE THREAD

**Issue by devlocalca** [cryzed/Selenium-Requests#35]
Greetings:

I am attempting to use the selenium-requests library and pass query string parameters.

I have something like:
    `self.driver.get(self.url_get)`

that works fine to get the page, but if I add:

```
data = {
  "param1": "data1",
  "param2": 'data2"
}
```

  `self.driver.get(self.url_get, data)  `

It fails.
--
There is no documentation on the main page:
   https://pypi.org/project/selenium-requests

about passing query string params, how is this accomplished with 'selenium-requests'?

Also same question about passing header data like:

```
headers = {
   <header-data-key-value-pairs-here>
} 
```

How do I pass query string params with Python GET

---

**Error:**

   'get() takes 2 positional arguments, but 3 were given'

'self' is the first argument, the URL is the 2nd positional argument, I am trying to pass 'data' as the third argument, and am getting the above error.

---

**Using:**

   from seleniumrequests import Chrome

Does anyone have a proven, working code snippet from a working example?

Thank You!

**Comment by OscarVanL** [comment]
Same question here, I want to add extra headers ontop of those my Selenium session already has, but it seems this library only copies the existing headers.

**Comment by cryzed** [comment]
Guys, please take a look at the README -- all your problems can be solved that way. In short:

As you can see [here](https://selenium-python.readthedocs.io/api.html#selenium.webdriver.support.event_firing_webdriver.EventFiringWebDriver.get), Selenium's WebDriver doesn't support any additional arguments to .get() -- so it doesn't "fail" or "only copy existing headers", it's expected behavior. The way to add extra headers and arguments and make non-GET requests (which is the whole point of Selenium-Requests), is to use the `.session` attribute of the Selenium-Requests webdriver, which is just a requests session object which synchronizes its _standard_ headers and cookies with the WebDriver.

This is clearly outlined in the README, so I'm confused why you are.
