### ISSUE TITLE
Support CookieJar instances for the cookies keyword

### ISSUE THREAD

**Issue by overwerk** [cryzed/Selenium-Requests#6]
cj = cookielib.CookieJar()
p = Firefox()
page = p.request('GET', 'https://www.google.com', headers=headers, cookies=cj)

returns:
File "/Library/Python/2.7/site-packages/seleniumrequests/request.py", line 215, in request
    cookies.update(kwargs['cookies'])

While 
s = requests.Session()
s.post(url, data=parameters, headers=headers, cookies=cj)

works just fine. 

Does anyone know why this error occurs?

**Comment by cryzed** [comment]
The error occurs because I wasn't aware that the requests library also accepts a CookieJar implementation instance for the cookies keyword-argument -- I only handle the case in which a dict is passed. For now you can work around this by manually turning your CookieJar instance into a dict by mapping all cookie names to their respective values for the given domain you are requesting.

**Comment by cryzed** [comment]
I won't implement this for now.
