### ISSUE TITLE
Not returning a http response code when using PhantomJS

### ISSUE THREAD

**Issue by bowlej** [cryzed/Selenium-Requests#7]
I have a selenium test that i have been using that goes to a list of pages and checks the http response code using the selenium-Requests module.

I have been running these tests fine when using the firefox webdriver but when i switch to using PhantomJS i don't get a response back and the tests runs indefinitely (Unless i use the page_load_timeout and then it get a timeout exception)

Not sure what i am doing wrong. See below for code that does work (Using Firefox weddriver)

    import unittest
    from seleniumrequests import Firefox

    class flyout_test(unittest.TestCase):
         def setUp(self):
             self.wd = Firefox()
             self.wd.maximize_window()
             self.wd.implicitly_wait(10)

         def test_page(self):
             Page = self.wd.request("GET", "http://google.com")
             print (Page)

         def tearDown(self):
             self.wd.quit()

    if __name__ == '__main__':
        unittest.main()

If i change the code to this i dont get back a response:

    import unittest
    from seleniumrequests import PhantomJS

    class flyout_test(unittest.TestCase):
         def setUp(self):
             self.wd = PhantomJS()
             self.wd.maximize_window()
             self.wd.implicitly_wait(10)

         def test_page(self):
             Page = self.wd.request("GET", "http://google.com")
             print (Page)

         def tearDown(self):
             self.wd.quit()

    if __name__ == '__main__':
        unittest.main()

Any help would be much appricated!

**Comment by cryzed** [comment]
Did you try running the test with an older PhantomJS version? When I released 1.3 I noticed that the tests failed for PhantomJS too, until I switched to an [older version](https://bitbucket.org/ariya/phantomjs/downloads/): 1.9.8. Since there were no issues mentioning this problem, I had assumed it was specific to my system configuration and didn't put it in the readme or try to investigate it any further.

For now please try that and report back. At this point I would actually go as far as simply not recommending using PhantomJS with Selenium-Requests or even deprecating support for it entirely, because it has unfortunately always been very unreliable and problematic. If all else fails, maybe try getting [SlimerJS](https://slimerjs.org/) to work.

**Comment by bowlej** [comment]
Ok, thanks for the reply, i will try the older version of phantomJS and see if i do get a response back.

**Comment by bowlej** [comment]
Version 1.9.8 did work for me, thanks again.
